on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      GO_VERSION: 1.17.1

    steps:
      - name: Checks out repository
        uses: actions/checkout@v2

      - name: Set up go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install go pre-commit dependencies
        run: "go get -u golang.org/x/lint/golint
          && go get golang.org/x/tools/cmd/goimports
          && go get github.com/fzipp/gocyclo/cmd/gocyclo
          && go mod tidy"
      - name: Run pre-commit hooks.
        uses: pre-commit/action@v2.0.3
